export const PERMISSION_CODES = [
  "clients.view_all",
  "clients.view_assigned",
  "clients.create",
  "clients.edit",
  "users.create",
  "users.edit",
  "users.deactivate",
  "demands.create",
  "demands.edit",
  "demands.assign",
  "demands.change_deadline",
  "demands.change_priority",
  "indicators.view",
  "productivity.view",
  "timers.view",
  "history.view",
  "projects.create",
  "shoots.create",
  "demands.extra_create",
  "portal.release_info",
  "portal.view",
  "portal.view_as_client",
  "settings.access",
  "reports.view",
  "roles.manage",
  "boards.manage_lists",
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];

export const PERMISSION_LABELS: Record<PermissionCode, string> = {
  "clients.view_all": "Visualizar todos os clientes",
  "clients.view_assigned": "Visualizar clientes atribuídos",
  "clients.create": "Criar cliente",
  "clients.edit": "Editar cliente",
  "users.create": "Criar usuário",
  "users.edit": "Editar usuário",
  "users.deactivate": "Desativar usuário",
  "demands.create": "Criar demanda",
  "demands.edit": "Editar demanda",
  "demands.assign": "Alterar responsável",
  "demands.change_deadline": "Alterar prazo",
  "demands.change_priority": "Alterar prioridade",
  "indicators.view": "Visualizar indicadores",
  "productivity.view": "Visualizar produtividade",
  "timers.view": "Visualizar cronômetros",
  "history.view": "Visualizar histórico",
  "projects.create": "Criar projeto",
  "shoots.create": "Criar captação",
  "demands.extra_create": "Criar demanda extra",
  "portal.release_info": "Liberar informação para cliente",
  "portal.view": "Visualizar portal do cliente",
  "portal.view_as_client": "Visualizar como cliente",
  "settings.access": "Acessar configurações",
  "reports.view": "Acessar relatórios",
  "roles.manage": "Gerenciar funções e permissões",
  "boards.manage_lists": "Gerenciar colunas do quadro",
};
